### ISSUE TITLE
Generated files crudl.js and crudl.min.js with npm or gulp doesn't works fine.

### ISSUE THREAD

**Issue by juanelojga** [crudlio/crudl#37] opened 2017-06-23 22:51 UTC
When I use the generated files (crudl.js or crudl.min.js) using `npm run build` or `gulp build`, I have errors like: "Uncaught TypeError: registeredFields.reduce is not a function". When I use the original files, all works fine.

I need to change a little part of code, that's why I need to generate that files.
It's fine to use `npm run build` or `gulp build`?
What I'm doing wrong?

**Comment by benwilhelm** [comment] 2017-06-26 16:06
I've seen the same behavior building the most recent version from source. It appears that `form.registeredFields` is somehow only taking the value of the first element defined in the views' `fields` property

Meaning, that for a view's fields defined this way:

    fields: [
        {
            name: 'email',
            label: 'Email',
            field: 'Text',
        },
        {
            name: 'password',
            label: 'Password',
            field: 'Password',
        }
    ]

form.registeredFields ends up as simply the last element in the array, like so:

    $ console.log(form.registeredFields)
    // yields object, not array
    {
        name: 'email',
        label: 'Email',
        field: 'Text',
    }

**Comment by sehmaschine** [comment] 2017-07-10 15:49
Can you please try again with the latest release (I have not been able to reproduce this).
I'm closing this for now, but feel free to reopen if the issue still exists.

**Comment by sehmaschine** [comment] 2017-12-29 13:35
I've tried again to reproduce this issue, but I'm not able to.

@vam Can you please take a look as well. I've tried with both master and 0.4 and didn't run into this.

**Comment by cusspvz** [comment] 2018-01-20 19:36
I'm seeing this issue as well on latest `master` branch.

Steps for reproducing it:
- remove the `node_modules` folder
- reinstall node modules
- run `npm run build`
- setup a view with more than one filter


<img width="458" alt="screen shot 2018-01-20 at 19 33 25" src="https://user-images.githubusercontent.com/3604053/35187253-d360a6fc-fe18-11e7-9a38-3814d0da1e00.png">

It throws an error stating it could not execute `reduce` because it does not exist.
It does not exist since the result is an `Object` instance.

<img width="453" alt="screen shot 2018-01-20 at 19 36 02" src="https://user-images.githubusercontent.com/3604053/35187269-350a5376-fe19-11e7-9e5f-0f6196342dc5.png">

**Comment by cusspvz** [comment] 2018-01-20 20:02
Got it, think it is related with `redux-form`, I think `registeredFields` was an `Array` instance and they might have change it to an `Object` instance. Going deeper.

**Comment by cusspvz** [comment] 2018-01-20 20:19
Fixed the `redux-form` version to the one stated at `package.json` and it worked.

` package.json `
```diff
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.1.0",
+    "redux-form": "6.2.1",
-    "redux-form": "^6.2.1",
    "redux-localstorage": "^1.0.0-rc5",
    "redux-localstorage-filter": "^0.1.1",
```

**Comment by georgeawwad** [comment] 2018-01-28 22:40
Not a great solution if you're running `react@^16.0.0` since  older packages that reference React.PropTypes will break your app.

**Comment by cusspvz** [comment] 2018-01-29 12:36
Crudl [is not yet](https://github.com/crudlio/crudl/blob/master/package.json#L116) using `react@16`.

**Comment by vam** [comment] 2018-02-13 17:58
I'm going to merge this in the master. Thanks @cusspvz  

We're working on `crudl 0.4` and we'll try to accommodate the latest versions of redux-forms (or final-forms maybe -- still to be decided) and switch to `react@16`

> Just a side note: I could reproduce this bug with npm but not with yarn. The difference being, npm installed `redux-form@6.8.0` whereas yarn installed `redux-form@6.4.3`

**Closed by vam** 2018-02-13 17:58 UTC
